name: Deploy Bedrock Lambda
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - bedrock/apps/bedrock/**/*

defaults:
  run:
    working-directory: bedrock/apps/bedrock

jobs:
  deploy:
    name: 'Deploy Lambda'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.24.1'

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build Lambda
        run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o build/ .

        # The lambda requires that the executing file be named "bootstrap"
      - name: Rename file
        run: mv ./build/bedrock ./build/bootstrap

      - name: Zip build
        run: zip -r -j main.zip ./build

      - name: Update Lambda code
        run: aws lambda update-function-code --function-name=bedrock --zip-file=fileb://main.zip
